POST http://localhost:5000/register-biz
Content-Type: application/json

{
  "name": "Sua saja 2",
  "meta": [
    { "meta_key": "whatsapp", "meta_value": "6282354566666" },
    { "meta_key": "address", "meta_value": "Amuntai Tengah" }
  ]
}