# ----------     BIZ API     ----------
###
POST http://localhost:5000/api/v1/biz
Content-Type: application/json

{
  "name": "NW Store",
  "meta": [
    {"meta_key": "address", "meta_value": "Barabai", "meta_extra": ""},
    {"meta_key": "whatsapp", "meta_value": "081316589945", "meta_extra": ""}
  ]
}

###
GET http://localhost:5000/api/v1/biz

###
GET http://localhost:5000/api/v1/biz/2

###
DELETE http://localhost:5000/api/v1/biz/3





# ----------     AUTH API     ----------
###
POST http://localhost:5000/api/v1/login
Content-Type: application/json

{
  "username": "akhyaar",
  "password": "123"
}