POST http://localhost:5000/register-biz
Content-Type: application/json

{
  "name": "PT. APALAH",
  "meta": [
    { "meta_key": "whatsapp", "meta_value": "6285250661542" },
    { "meta_key": "address", "meta_value": "Sungai Malang" }
  ]
}

###
GET http://localhost:5000/register-biz